### ISSUE TITLE
Crash when joining call

### ISSUE THREAD

**Issue by UTrosh** [Florent-Marc/SPhone#2]
Server logs :
[17:39:59 INFO]: [voicechat] Player eKiff (8d3cd3af-3c96-3e6b-a545-5168a427004c) successfully connected to voice chat
[17:40:16 INFO]: addPlayertoCall : 47728 doesn't exists
[17:40:16 INFO]: addPlayertoCall : 47728 exists
[17:40:16 INFO]: eKiff lost connection: Disconnected
[17:40:16 INFO]: [voicechat] Disconnecting client eKiff

Client logs:
[18:40:16] [Netty Client IO #1/ERROR] [FML]: SimpleChannelHandlerWrapper exception
java.lang.NoSuchFieldError: showGroupHUD
	at com.dev.sphone.mod.common.packets.client.PacketPlayerHudState$Handler.onMessage(PacketPlayerHudState.java:35) ~[PacketPlayerHudState$Handler.class:1.3.0]
	at com.dev.sphone.mod.common.packets.client.PacketPlayerHudState$Handler.onMessage(PacketPlayerHudState.java:31) ~[PacketPlayerHudState$Handler.class:1.3.0]

**Comment by gabidut** [comment]
Hi, can you send the full list of installed mods ?

On server and on client.

**Comment by UTrosh** [comment]
On server (and client bc there are same mods) : 
![image](https://github.com/Florent-Marc/SPhone/assets/73399986/51892b91-4999-4c57-9198-0fc99241db9c)

**Comment by UTrosh** [comment]
is it fixed with latest commit?

**Comment by gabidut** [comment]
No, I think it's problem with the version of voicechat but I have to investigate more.

**Comment by UTrosh** [comment]
okok

**Comment by Sarocesch** [comment]
Voice Chat version 2.4.13 works

**Comment by UTrosh** [comment]
i'll test it tomorrow

**Comment by UTrosh** [comment]
working, ty
